line.bot:
  channel-token: 'g+DEjOWWSYqfh2dKoMEbqpw+iwDp4Gf0LVwHAcvU/szUWEphCAcj/BFssroQMuhPBE4asYUDdXeL4OduECEpbktvjz05PwG93TeFyJXO5gYHDKfxN438+7HtJlC8qch/uwEjrO+q5TP/xkBHkwi+qwdB04t89/1O/w1cDnyilFU='
  channel-secret: 'f3fe99681eb03bb34f8eb97047f9417b'
  handler.path: /callback